[package]
name = "sphur"
version = "0.1.0"
edition = "2024"
description = "Sphūr (स्फुर्) is a SIMD™ powered PRNG library."
license = "Apache-2.0"
repository = "https://github.com/frozen-lab/sphur"
keywords = ["prng", "simd", "random", "rng", "entropy", "seed"]

[dependencies]

[[bench]]
name = "bench"
path = "benchmarks/bench.rs"
harness = false
