[build]
target-dir = "target"

[target.'cfg(target_arch = "x86_64")']
rustflags = [
  "-C", "target-cpu=native",
  "-C", "target-feature=+sse2,+ssse3,+sse4.1,+sse4.2,+avx,+avx2",
]

[target.'cfg(target_arch = "aarch64")']
rustflags = [
  "-C", "target-cpu=native",
  "-C", "target-feature=+neon",
]
