[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "target-feature=+ssse3,+sse4.1,+sse4.2"
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "target-feature=+neon,+asimd"
]
