name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  doc_tests:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            
          - os: ubuntu-24.04-arm
            arch: aarch64
            
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache-key: ${{ hashFiles('**/Cargo.lock') }}

      - name: Doc Tests
        run: RUSTFLAGS="-C target-cpu=native" cargo test --doc

  publish:
    needs: doc_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache-key: ${{ hashFiles('**/Cargo.lock') }}
  
      - name: Auth
        uses: rust-lang/crates-io-auth-action@v1
        id: auth
        
      - name: Publish to `crates.io`
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}  
          
  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache-key: ${{ hashFiles('**/Cargo.lock') }}

      - name: Run Benchmarks
        run: |
          taskset -c 0 cargo bench --bench basic

      - name: Prep Release Doc
        run: |
          chmod +x ./scripts/release.sh
          
          ./scripts/release.sh
          echo "Added changelog"
          
          cat .local/bench.md >> .local/release.md
          echo "Added bench results"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          body_path: .local/release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
