name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # allow manual trigger
  workflow_dispatch:

jobs:
  clib-test:
    strategy:
      fail-fast: false
      
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            use-flake: true
            
          - os: ubuntu-24.04-arm
            arch: aarch64
            use-flake: true

          - os: windows-latest
            arch: x86_64
            use-flake: false
            
          - os: windows-11-arm
            arch: aarch64
            use-flake: false

          - os: macos-13
            arch: x86_64
            use-flake: true
            
          - os: macos-latest
            arch: aarch64
            use-flake: true
            
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v1
        with:
          cache-version: 1
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Test aarch64 (NEON)
        if: matrix.arch == 'aarch64'
        run: cargo test --release -- --nocapture

      - name: Test x86_64 (SSE2)
        if: matrix.arch == 'x86_64'
        run: RUSTFLAGS="-C target-feature=+sse2" cargo test --release -- --nocapture

      - name: Test x86_64 (AVX2)
        if: matrix.arch == 'x86_64'
        run: RUSTFLAGS="-C target-feature=+avx2" cargo test --release -- --nocapture        
