name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  clib-test:
    strategy:
      fail-fast: false
      
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27

      - name: Build & Test clib
        working-directory: ./clib
        run: |
          nix develop .#clib --command bash -c "
            make
            make test
          "
