name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # allow manual trigger
  workflow_dispatch:

jobs:
  clib-test:
    strategy:
      fail-fast: false
      
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            use-flake: true
            
          - os: ubuntu-24.04-arm
            arch: aarch64
            use-flake: true

          - os: windows-latest
            arch: x86_64
            use-flake: false

          - os: macos-13
            arch: x86_64
            use-flake: true
            
          - os: macos-latest
            arch: aarch64
            use-flake: true
            
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      # MacOS x86_64 CPU check
      - name: Validate CPU Arch for MacOS (x84_64)
        if: matrix.os == 'macos-13'
        run: |
          if [ "$(uname -m)" != "x86_64" ]; then
            echo "Skipping: Not running on Intel MacOS (x86_64)"
            exit 0
          fi

      # Linux & MacOS (w/ Nix)
      - uses: cachix/install-nix-action@v27
        if: matrix.use-flake == true

      - name: Build & Test (Linux/MacOS)
        if: matrix.use-flake == true
        working-directory: ./clib
        run: |
          if [ "${{ matrix.arch }}" = "aarch64" ]; then
            nix develop .#clib_a64 --command bash -c "
              make
              make test
            "
          else
            nix develop .#clib_x64 --command bash -c "
              make
              make test
            "
          fi

      # Win (w/o Nix)
      - uses: msys2/setup-msys2@v2
        if: matrix.use-flake == false
        with:
          update: true
          install: >-
            make
            nasm
            mingw-w64-x86_64-gcc

      - name: Build & Test (Win)
        if: matrix.use-flake == false
        working-directory: ./clib
        shell: msys2 {0}
        run: |
          make
          make test
